### ISSUE TITLE
Error: Resize must be passed a displayed plot div element.

### ISSUE THREAD

**Issue by ryanjackman** [plotly/angular-plotly.js#41]
Related to #24 

I have produced a minimal reproduction here https://github.com/ryanjackman/angular-plotly.js/
Build & serve the app. Navigate to Box Plots, click button to hide plot, resize window, and observe the console for the error.

```
ERROR Error: Uncaught (in promise): Error: Resize must be passed a displayed plot div element.
Error: Resize must be passed a displayed plot div element.
```

This issue occurs when a plot is hidden with an *ngIf and the window is resized.

To create a responsive plot the README says set `useResizeHandler` to true in the template and set `autosize` true in the plot layout. This was not enough to make a responsive plot inside a flexbox. The plot would resize larger but not smaller.
I was able to get this to work by setting the plot's `config.responsive` to true.

It was setting `config.responsive` to true that caused the error to show up.

This is sort of a two part issue related to plots in flexboxes.
* When configured to be responsive, plots in flexboxes that have been hidden throw errors when resized.
* A plot is not fully responsive inside a flexbox when configured per the README
---
Seen in Chrome, not seen in Firefox.
angular-plotly.js 1.0.1
plotly.js 1.43.1

**Comment by whythecode** [comment]
yep, unfortunately I fought with this issue for quite a bit until I figured out the problem...

In the plotly.js library, when this setting is set, a window event handler is added:
https://github.com/plotly/plotly.js/blob/b03bb3b01a851e201ebf98341144ca11a414378d/src/plot_api/plot_api.js#L194

This event handler is then only removed when clearResponsive is called: 
- https://github.com/plotly/plotly.js/blob/b03bb3b01a851e201ebf98341144ca11a414378d/src/plot_api/plot_api.js#L203
- https://github.com/plotly/plotly.js/blob/c34d299f1671938ba3aa41bfe6cecca4ee1859e8/src/plots/plots.js#L1650

This is seemingly not done anywhere by the angular-plotly lib. Only the lib's own resize event is cleared.
OnDestroy: https://github.com/plotly/angular-plotly.js/blob/581ea6beb9da2e2af20c057bd5b4c345e5949868/src/app/shared/plot/plot.component.ts#L109
Service.remove: https://github.com/plotly/angular-plotly.js/blob/581ea6beb9da2e2af20c057bd5b4c345e5949868/src/app/shared/plotly.service.ts#L24

So whenever the component is removed from the view, the listener from plotly is still there and then throws an error.

**Comment by whythecode** [comment]
fyi - added PR #45, which should fix the issue (does on my project at least) :-)

**Comment by nicolaskruchten** [comment]
@antoinerg should we be clearing something that we’re not?

**Comment by nathankeeney** [comment]
This is still occurring for me in 1.3.0. I am loading/unloading Plotly charts via Angular-Router, and the resize handler is not getting cleared.

**Comment by antoinerg** [comment]
@nicolaskruchten @nathankeeney 

On the `plotly.js` side of things, we clear the responsive handler (which is an event listener on the window) when `Plotly.purge` is called. If you remove a graph div manually and resize the window, plotly.js will try to resize an inexistent div and will return an error.

Either:
1. The user calls `Plotly.purge` to get rid of a graph div
2. Or on resize, we check if the graph element is in the DOM and we remove the event listener when it's not.

https://github.com/plotly/plotly.js/blob/36b4773497870621ed5257119e6a26ace78e18a0/src/plot_api/plot_api.js#L184-L194

**Comment by markzolotoy** [comment]
I am getting the same error. Is it still supposed to happen? If yes, any workaround?

**Comment by ryanjackman** [comment]
The 1.1.0 release with @whythecode's fix solved this problem for me and I wouldn't expect this to still be an issue. Not sure why you would still be seeing this and I never found a workaround.

**Comment by markzolotoy** [comment]
What release are you talking about?

**Comment by Levi-Montgomery** [comment]
I had the exact same problem. My thing was that I was using [hidden]=isHidden and hiding/showing the plot. I needed the plot to still be in the DOM because I am writing data to it even when it's not shown, and I didn't want to lose anything so purging was not a viable path for me.

 But, I was able to find a workaround. I merely observe the plot, when its visible, i resize it.
 
```typescript
 Something like 
   private observePlotDiv(div: HTMLElement) {
    const observer = new MutationObserver((mutations) => {
      mutations.forEach(() => {
        PlotlyJS.Plots.resize(div);
      });
    });
    observer.observe(div, { attributes: true });
  }
```
  
  Might not work in Internet Explorer though.
